#include"TrainHeadfile.h"
#include"egg.h"
void Creatmap(TrainInfo train[4]){
	EggStart(1440,900);	
	backdrop=LayEgg();
	DrawBitmap("backdrop.bmp");
	rail=LayEgg();
	MovePen(50,900-50);     
	SetPenColor(RED);
	SetPenWidth(6);
	DrawLine(0,-train[1].train_orbit_W*1.5);    
	DrawLine(train[1].train_orbit_L*1.5,0);	
	DrawLine(0,train[1].train_orbit_W*1.5);				
	DrawLine(-train[1].train_orbit_L*1.5,0);
	OffsetPen(train[1].train_orbit_L*7.5-25,-train[1].train_orbit_W*7.5);
	DrawString("A车轨道");
	MovePen(50+train[1].train_orbit_L*1.5,900-50-train[2].train_datum_point.y*1.5); 
	SetPenColor(YELLOW);
	DrawLine(0,-train[2].train_orbit_W*1.5);
	SetPenColor(GREEN);    
	DrawLine(train[2].train_orbit_L*1.5,0);	
	DrawLine(0,train[2].train_orbit_W*1.5);	
	DrawLine(-train[2].train_orbit_L*1.5,0);
	OffsetPen(train[2].train_orbit_L*7.5-25,-train[2].train_orbit_W*7.5);
	DrawString("B车轨道");
	MovePen(50+train[3].train_datum_point.x*1.5,900-50-train[1].train_orbit_W*1.5); 
	SetPenColor(CYAN); 
	DrawLine(0,-train[3].train_orbit_W*1.5); 
	DrawLine(train[3].train_orbit_L*1.5,0);	
	DrawLine(0,train[3].train_orbit_W*1.5);
	SetPenColor(YELLOW);				
	DrawLine(-train[3].train_orbit_L*1.5,0);
	OffsetPen(train[3].train_orbit_L*7.5-25,-train[3].train_orbit_W*7.5);
	SetPenColor(CYAN);
	DrawString("C车轨道");
	MovePen(1200,750);
	DrawBitmap("Button1.bmp");
	OffsetPen(20,0);
	DrawBitmap("Button2.bmp");
	OffsetPen(-100,-90);
	DrawBitmap("Button4.bmp");
	OffsetPen(-220,0);
	DrawBitmap("Button3.bmp");
	OffsetPen(-100,-90);
	DrawBitmap("Button5.bmp");
	OffsetPen(20,0);
	DrawBitmap("Button6.bmp");
	OffsetPen(-100,-90);
	DrawBitmap("Button8.bmp");
	OffsetPen(-220,0);
	DrawBitmap("Button7.bmp");
	SetPenColor(WHITE);
	SetPenWidth(10);
	MovePen(100,180);
	DrawString("A-B公轨");
	double x;
	x=GetPenXPos()-100;
	OffsetPen(-x,-80);
	DrawString("A-C公轨");
	MovePen(500,180);
	DrawString("运行策略：");
	MovePen(500,120);
	DrawString("当前时间：");
	MovePen(700,180);
	DrawString("A暂停时间(0.1s)：");
	MovePen(700,140);
	DrawString("B暂停时间(0.1s)：");
	MovePen(700,100);
	DrawString("C暂停时间(0.1s)：");
	lightR1=LayEgg();
	TA=LayEgg();
	MovePen(25,900-25);
	if(train[1].train_start_1D<=train[1].train_orbit_L)
	OffsetPen(train[1].train_start_1D*1.5,0);
	if(train[1].train_start_1D<=train[1].train_orbit_L+train[1].train_orbit_W&&train[1].train_start_1D>train[1].train_orbit_L)
	OffsetPen(train[1].train_orbit_L*1.5,-(train[1].train_start_1D-train[1].train_orbit_L)*1.5);
	if(train[1].train_start_1D>train[1].train_orbit_L+train[1].train_orbit_W&&train[1].train_start_1D<=2*train[1].train_orbit_L+train[1].train_orbit_W)
	OffsetPen(train[1].train_orbit_L*1.5-(train[1].train_start_1D-train[1].train_orbit_L-train[1].train_orbit_W)*1.5,-train[1].train_orbit_W*1.5);
	if(train[1].train_start_1D<=(train[1].train_orbit_L+train[1].train_orbit_W)*2&&train[1].train_start_1D>2*train[1].train_orbit_L+train[1].train_orbit_W)
	OffsetPen(0,-train[1].train_orbit_W*1.5+(train[1].train_start_1D-train[1].train_orbit_L*2-train[1].train_orbit_W)*1.5);
	DrawBitmap("TA.bmp");
	TB=LayEgg();
	MovePen(25+train[1].train_orbit_L*1.5,900-25-train[2].train_datum_point.y*1.5);
	if(train[2].train_start_1D<=train[2].train_orbit_L)
	OffsetPen(train[2].train_start_1D*1.5,0);
	if(train[2].train_start_1D<=train[2].train_orbit_L+train[2].train_orbit_W&&train[2].train_start_1D>train[2].train_orbit_L)
	OffsetPen(train[2].train_orbit_L*1.5,-(train[2].train_start_1D-train[2].train_orbit_L)*1.5);
	if(train[2].train_start_1D>train[2].train_orbit_L+train[2].train_orbit_W&&train[2].train_start_1D<=2*train[2].train_orbit_L+train[2].train_orbit_W)
	OffsetPen(train[2].train_orbit_L*1.5-(train[2].train_start_1D-train[2].train_orbit_L-train[2].train_orbit_W)*1.5,-train[2].train_orbit_W*1.5);
	if(train[2].train_start_1D<=(train[2].train_orbit_L+train[2].train_orbit_W)*2&&train[2].train_start_1D>2*train[2].train_orbit_L+train[2].train_orbit_W)
	OffsetPen(0,-train[2].train_orbit_W*1.5+(train[2].train_start_1D-train[2].train_orbit_L*2-train[2].train_orbit_W)*1.5);
	DrawBitmap("TB.bmp");
	TC=LayEgg();
	MovePen(25+train[3].train_datum_point.x*1.5,900-25-train[1].train_orbit_W*1.5);
	if(train[3].train_start_1D<=train[3].train_orbit_L)
	OffsetPen(train[3].train_start_1D*1.5,0);
	if(train[3].train_start_1D<=train[3].train_orbit_L+train[3].train_orbit_W&&train[3].train_start_1D>train[3].train_orbit_L)
	OffsetPen(train[3].train_orbit_L*1.5,-(train[3].train_start_1D-train[3].train_orbit_L)*1.5);
	if(train[3].train_start_1D>train[3].train_orbit_L+train[3].train_orbit_W&&train[3].train_start_1D<=2*train[3].train_orbit_L+train[3].train_orbit_W)
	OffsetPen(train[3].train_orbit_L*1.5-(train[3].train_start_1D-train[3].train_orbit_L-train[3].train_orbit_W)*1.5,-train[3].train_orbit_W*1.5);
	if(train[3].train_start_1D<=(train[3].train_orbit_L+train[3].train_orbit_W)*2&&train[3].train_start_1D>2*train[3].train_orbit_L+train[3].train_orbit_W)
	OffsetPen(0,-train[3].train_orbit_W*1.5+(train[3].train_start_1D-train[3].train_orbit_L*2-train[3].train_orbit_W)*1.5);
	DrawBitmap("TC.bmp");


}
